# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: 'postgres'
    secrets:
      - db_password
  blazor-server:
    image: blazor-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ConnectionStrings__Trainor: null
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/Trainor.Wasm.Server.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: 80a75217-d1e7-4076-a031-2de6dba5361d
    ports:
      - 7208:80
      - 7207:443
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStrings__Trainor
    volumes:
      - ../aspnet/https:/https/

secrets:
  connection_string:
    file: ../connection_string.txt
  db_password:
    file: ../db_password.txt
